import { Led } from "./panels";


export const spot: Array<Led> = [
    {
        title: 'SAPRA SP001',
        color: 'белый',
        article: '2200077',
        diameter: 'Ø55×100мм',
        patron: 'GU10',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200077.jpg',
        price: '3.26'
      },
      {
        title: 'SAPRA SP001',
        color: 'чёрный',
        article: '2200078',
        diameter: 'Ø55×100мм',
        patron: 'GU10',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200078.jpg',
        price: '3.26'
      },
      {
        title: 'SAPRA SP002',
        color: 'белый',
        article: '2200079',
        diameter: 'Ø68×100мм',
        patron: 'GU10',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200079.jpg',
        price: '5.00'
      },
      {
        title: 'SAPRA SP002',
        color: 'чёрный',
        article: '2200080',
        diameter: 'Ø68×100мм',
        patron: 'GU10',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200080.jpg',
        price: '5.00'
      },
      {
        title: 'SAPRA SP004',
        color: 'белый',
        article: '2200083',
        diameter: '60×60×100мм',
        patron: 'GU10',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200083.jpg',
        price: '6.00'
      },
      {
        title: 'SAPRA SP004',
        color: 'чёрный',
        article: '2200084',
        diameter: '60×60×100мм',
        patron: 'GU10',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200084.jpg',
        price: '6.00'
      },
      {
        title: 'SAPRA SP005',
        color: 'белый',
        article: '2200085',
        diameter: 'Ø62×100мм',
        patron: 'GU10',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200085.jpg',
        price: '5.90'
      },
      {
        title: 'SAPRA SP005',
        color: 'чёрный',
        article: '2200086',
        diameter: 'Ø62×100мм',
        patron: 'GU10',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200086.jpg',
        price: '5.90'
      },
      {
        title: 'SAPRA SP006',
        color: 'белый',
        article: '2200087',
        diameter: 'Ø62×130мм',
        patron: 'GU10',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200087.jpg',
        price: '8.80'
      },
      {
        title: 'SAPRA SP006',
        color: 'чёрный',
        article: '2200088',
        diameter: 'Ø62×130мм',
        patron: 'GU10',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200088.jpg',
        price: '8.80'
      },
      {
        title: 'SAPRA SP007',
        color: 'белый',
        article: '2200257',
        diameter: 'Ø83×70мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200257.jpg',
        price: '3.40'
      },
      {
        title: 'SAPRA SP007',
        color: 'чёрный',
        article: '2200258',
        diameter: 'Ø83×70мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200258.jpg',
        price: '3.40'
      },
      {
        title: 'SAPRA SP008',
        color: 'белый',
        article: '2200259',
        diameter: '85×85×63мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200259.jpg',
        price: '4.37'
      },
      {
        title: 'SAPRA SP008',
        color: 'чёрный',
        article: '2200260',
        diameter: '85×85×63мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200260.jpg',
        price: '4.37'
      },
      {
        title: 'SAPRA SP010',
        color: 'белый',
        article: '2200089',
        diameter: 'Ø85×70мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200089.jpg',
        price: '6.41'
      },
      {
        title: 'SAPRA SP010',
        color: 'чёрный',
        article: '2200090',
        diameter: 'Ø85×70мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200090.jpg',
        price: '6.41'
      },
      {
        title: 'SAPRA SP018',
        color: 'белый',
        article: '2200271',
        diameter: 'Ø85×80мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл + стекло',
        img: '/img/lamps/spot/2200271.jpg',
        price: '7.20'
      },
      {
        title: 'SAPRA SP018',
        color: 'чёрный',
        article: '2200272',
        diameter: 'Ø85×80мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл + стекло',
        img: '/img/lamps/spot/2200272.jpg',
        price: '7.20'
      },
      {
        title: 'SAPRA SP019',
        color: 'белый',
        article: '2200273',
        diameter: 'Ø82×60мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200273.jpg',
        price: '5.50'
      },
      {
        title: 'SAPRA SP019',
        color: 'чёрный',
        article: '2200274',
        diameter: 'Ø82×60мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200274.jpg',
        price: '5.50'
      },
      {
        title: 'SAPRA SP020',
        color: 'белый',
        article: '2200275',
        diameter: 'Ø90×53мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200275.jpg',
        price: '3.35'
      },
      {
        title: 'SAPRA SP020',
        color: 'чёрный',
        article: '2200276',
        diameter: 'Ø90×53мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл',
        img: '/img/lamps/spot/2200276.jpg',
        price: '3.35'
      },
      {
        title: 'SAPRA SP021',
        color: 'белый',
        article: '2200277',
        diameter: 'Ø83×72мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл + стекло',
        img: '/img/lamps/spot/2200277.jpg',
        price: '4.50'
      },
      {
        title: 'SAPRA SP021',
        color: 'чёрный',
        article: '2200278',
        diameter: 'Ø83×72мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл + стекло',
        img: '/img/lamps/spot/2200278.jpg',
        price: '4.50'
      },
      {
        title: 'SAPRA SP022',
        color: 'белый',
        article: '2200279',
        diameter: 'Ø85×70мм',
        patron: 'GX53',
        rotation: 'нет',
        material: 'металл + стекло',
        img: '/img/lamps/spot/2200279.jpg',
        price: '4.40'
      },
      {
        title: 'SAPRA SP003',
        color: 'белый',
        article: '2200081',
        diameter: 'Ø55×147мм',
        patron: 'GU10',
        rotation: 'есть',
        material: 'металл + пластик',
        img: '/img/lamps/spot/2200081.jpg',
        price: '7.50'
      },
      {
        title: 'SAPRA SP003',
        color: 'чёрный',
        article: '2200082',
        diameter: 'Ø55×147мм',
        patron: 'GU10',
        rotation: 'есть',
        material: 'металл + пластик',
        img: '/img/lamps/spot/2200082.jpg',
        price: '6.50'
      },
      {
        title: 'SAPRA SP016-1',
        color: 'белый',
        article: '2200263',
        diameter: 'Ø80×115мм',
        patron: 'GX53',
        rotation: 'есть',
        material: 'металл',
        img: '/img/lamps/spot/2200263.jpg',
        price: '6.66'
      },
      {
        title: 'SAPRA SP016-1',
        color: 'чёрный',
        article: '2200264',
        diameter: 'Ø80×115мм',
        patron: 'GX53',
        rotation: 'есть',
        material: 'металл',
        img: '/img/lamps/spot/2200264.jpg',
        price: '6.66'
      },
      {
        title: 'SAPRA SP016-2',
        color: 'белый',
        article: '2200265',
        diameter: '265×80×120мм',
        patron: 'GX53',
        rotation: 'есть',
        material: 'металл',
        img: '/img/lamps/spot/2200265.jpg',
        price: '15.46'
      },
      {
        title: 'SAPRA SP016-2',
        color: 'чёрный',
        article: '2200266',
        diameter: '265×80×120мм',
        patron: 'GX53',
        rotation: 'есть',
        material: 'металл',
        img: '/img/lamps/spot/2200266.jpg',
        price: '15.46'
      },
      {
        title: 'SAPRA SP016-3',
        color: 'белый',
        article: '2200267',
        diameter: '365×80×120мм',
        patron: 'GX53',
        rotation: 'есть',
        material: 'металл',
        img: '/img/lamps/spot/2200267.jpg',
        price: '22.08'
      },
      {
        title: 'SAPRA SP016-3',
        color: 'чёрный',
        article: '2200268',
        diameter: '365×80×120мм',
        patron: 'GX53',
        rotation: 'есть',
        material: 'металл',
        img: '/img/lamps/spot/2200268.jpg',
        price: '22.08'
      },
      {
        title: 'SAPRA SP017',
        color: 'белый',
        article: '2200269',
        diameter: 'Ø82×80мм',
        patron: 'GX53',
        rotation: 'есть',
        material: 'металл',
        img: '/img/lamps/spot/2200269.jpg',
        price: '7.90'
      },
      {
        title: 'SAPRA SP017',
        color: 'чёрный',
        article: '2200270',
        diameter: 'Ø82×80мм',
        patron: 'GX53',
        rotation: 'есть',
        material: 'металл',
        img: '/img/lamps/spot/2200270.jpg',
        price: '7.90'
      }
]